# Generated by Django 3.1.7 on 2021-03-26 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(default='select', max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='Enter the product name', max_length=255)),
                ('productDetails', models.TextField(default='Enter product details \nExample: \nProduct Name: \nProduct Id: \nBrand Name \nProduct Categories: \netc', max_length=3500)),
                ('productPrice', models.FloatField(default=0)),
                ('productImage', models.ImageField(upload_to='media/productImage')),
                ('productQuantity', models.IntegerField(default=1)),
                ('publishedDate', models.DateTimeField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
        ),
    ]
